server:
  port: 6666

#STRIPE_SECRET_KEY : sk_test_51IZ2zyB7fkZfvOQILz1ofC7nVyozMMi5bxbFz10AftRj1cglU0fpRESXuYDRtKUCQDresRwUa1aaQlbZq3xhWlnc00faawks0R
#STRIPE_PUBLIC_KEY : pk_test_51IZ2zyB7fkZfvOQIxhO16NXQZdhVl6Y2S2HBt0mkZyUcl5BFwIPVtehutuqer59KMtms3GlrTd79rulhGgNhlfpa00GaKfuV57

STRIPE_SECRET_KEY : sk_test_51IoXeyDxEwQ9enN7XM4Zcpy2iUKEPFSMXI44XnrCjPrs9AGOmX1cltUJ3TO5yqd0JbO68F1c1pWxCXT5IHhHi9M200H63fOQlJ
STRIPE_PUBLIC_KEY : pk_test_51IoXeyDxEwQ9enN7rk4ziQgnaqGYnF4aVR2jTEQ3Jr3fWmAV7h4HwEpBGYxjJPOP9HFPKIhN2xnARc7t5V2aXLoX005NBF37CV

payment:
  purge:
    # 6 hrs
    frequency: 21600000
    initial-delay: 60000